config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # Remove the individual get routes since they're handled by resources
  resources :streaming_services, only: [:index, :show] do
    collection do
      get 'connect_spotify'
    end
  end
  
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
     # @playlists = current_user.spotify_playlists
    else
      @playlists = []
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid min-vh-100" style="background-color: #1e2124;">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-5 mt-5">
        <div class="card bg-dark text-white p-4" style="border-radius: 15px;">
          <div class="card-body">
            <% if current_user %>
              <div class="d-grid gap-3">
                <%= link_to "My Streaming Services", streaming_services_path, 
                    class: "btn btn-primary btn-lg btn-block" %>
                <%= link_to "Edit Account", edit_user_registration_path, 
                    class: "btn btn-outline-light btn-lg btn-block" %>
                <%= button_to "Logout", destroy_user_session_path, 
                    data: {turbo: "false"}, method: :delete, 
                    class: "btn btn-danger btn-lg btn-block" %>
              </div>
            <% else %>
              <div class="d-grid gap-3">
                <%= link_to "Login", new_user_session_path, 
                    class: "btn btn-primary btn-lg btn-block" %>
              </div>
              <div class="text-center mt-3">
                <small class="text-muted">
                  Don't have an account? <%= link_to "Create Account", new_user_registration_path, 
                    class: "btn btn-outline-light btn-lg btn-block" %>
                </small>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>